export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const CANCEL_ADDING_TO_MENU = 'CANCEL_ADDING_TO_MENU';
export const ENABLE_ADDING_TO_MENU = 'ENABLE_ADDING_TO_MENU';
export const CHANGE_BURGER_NAME = 'CHANGE_BURGER_NAME';

export const FETCH_BURGERS_START = 'FETCH_BURGERS_START';
export const FETCH_BURGERS_SUCCESS = 'FETCH_BURGERS_SUCCESS';
export const FETCH_BURGERS_FAIL = 'FETCH_BURGERS_FAIL';

export const ADD_TO_MENU_START = 'ADD_TO_MENU_START';
export const ADD_TO_MENU_SUCCESS = 'ADD_TO_MENU_SUCCESS';
export const ADD_TO_MENU_FAIL = 'ADD_TO_MENU_FAIL';
