export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const CHANGE_BURGER_NAME = 'CHANGE_BURGER_NAME';
export const CANCEL_ADDING_TO_MENU = 'CANCEL_ADDING_TO_MENU';
export const ENABLE_ADDING_TO_MENU = 'ENABLE_ADDING_TO_MENU';